import type { AuditLogEntry, AccessAttempt } from "@/lib/types"

export const initialAuditLogs: AuditLogEntry[] = [
  {
    id: "log-001",
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    userId: "usr-001",
    userName: "Dr. Sarah Chen",
    userRole: "clinician",
    action: "VIEW",
    resource: "Patient Record - MRN-2024-001",
    details: "Accessed patient vital signs and medication history",
    ipAddress: "192.168.1.45",
    success: true,
  },
  {
    id: "log-002",
    timestamp: new Date(Date.now() - 1000 * 60 * 12),
    userId: "usr-002",
    userName: "Tech Mike Wilson",
    userRole: "technician",
    action: "CONFIGURE",
    resource: "Vital Monitor Alpha (vs-001)",
    details: "Updated alarm thresholds for heart rate monitoring",
    ipAddress: "192.168.1.67",
    success: true,
  },
  {
    id: "log-003",
    timestamp: new Date(Date.now() - 1000 * 60 * 25),
    userId: "usr-003",
    userName: "Admin John Doe",
    userRole: "admin",
    action: "MODIFY",
    resource: "EHR Connection Settings",
    details: "Updated FHIR endpoint configuration for Epic integration",
    ipAddress: "192.168.1.10",
    success: true,
  },
  {
    id: "log-004",
    timestamp: new Date(Date.now() - 1000 * 60 * 35),
    userId: "usr-004",
    userName: "Dr. James Miller",
    userRole: "clinician",
    action: "EXPORT",
    resource: "Patient Data - Multiple Records",
    details: "Exported vitals summary for rounds report",
    ipAddress: "192.168.1.89",
    success: true,
  },
  {
    id: "log-005",
    timestamp: new Date(Date.now() - 1000 * 60 * 48),
    userId: "usr-005",
    userName: "Unknown",
    userRole: "technician",
    action: "ACCESS",
    resource: "Security Settings",
    details: "Attempted to access admin security panel",
    ipAddress: "192.168.1.234",
    success: false,
  },
  {
    id: "log-006",
    timestamp: new Date(Date.now() - 1000 * 60 * 60),
    userId: "usr-002",
    userName: "Tech Mike Wilson",
    userRole: "technician",
    action: "CONNECT",
    resource: "Infusion Pump B2 (ip-002)",
    details: "Established connection to EHR system",
    ipAddress: "192.168.1.67",
    success: true,
  },
  {
    id: "log-007",
    timestamp: new Date(Date.now() - 1000 * 60 * 75),
    userId: "usr-001",
    userName: "Dr. Sarah Chen",
    userRole: "clinician",
    action: "ACKNOWLEDGE",
    resource: "Critical Alert - ECG Monitor 2",
    details: "Acknowledged AFib alert for patient in CCU-202",
    ipAddress: "192.168.1.45",
    success: true,
  },
  {
    id: "log-008",
    timestamp: new Date(Date.now() - 1000 * 60 * 90),
    userId: "usr-003",
    userName: "Admin John Doe",
    userRole: "admin",
    action: "CREATE",
    resource: "User Account",
    details: "Created new technician account for night shift",
    ipAddress: "192.168.1.10",
    success: true,
  },
]

export const initialAccessAttempts: AccessAttempt[] = [
  {
    id: "acc-001",
    timestamp: new Date(Date.now() - 1000 * 60 * 48),
    userId: "usr-005",
    resource: "Security Settings",
    action: "ACCESS",
    granted: false,
    reason: "Insufficient permissions - Admin role required",
    ipAddress: "192.168.1.234",
  },
  {
    id: "acc-002",
    timestamp: new Date(Date.now() - 1000 * 60 * 120),
    resource: "Device Configuration",
    action: "MODIFY",
    granted: false,
    reason: "Invalid session token",
    ipAddress: "10.0.0.55",
  },
  {
    id: "acc-003",
    timestamp: new Date(Date.now() - 1000 * 60 * 180),
    resource: "Patient Records",
    action: "EXPORT",
    granted: false,
    reason: "Rate limit exceeded",
    ipAddress: "192.168.1.100",
  },
]

export const generateAuditLogEntry = (
  action: string,
  resource: string,
  details: string,
  userName: string,
  userRole: "admin" | "clinician" | "technician",
  success: boolean = true
): AuditLogEntry => ({
  id: `log-${Date.now()}`,
  timestamp: new Date(),
  userId: `usr-${Math.random().toString(36).substr(2, 9)}`,
  userName,
  userRole,
  action,
  resource,
  details,
  ipAddress: `192.168.1.${Math.floor(Math.random() * 254) + 1}`,
  success,
})
